### ISSUE TITLE
File is uploaded with ziro size (What will be second parameter in upload function?)

### ISSUE THREAD

**Issue by dhara15101991** [dcblogdev/laravel-dropbox#2]
I am trying to upload the file with the following code:

```
$filename = $request->file->getClientOriginalName();
$name     = md5($filename . time()) . '.' . $request->file->getClientOriginalExtension();
$path     = Storage::disk('local')->putFileAs('uploaded_files', $request->file('file'), $name);
$imagePath = Storage::path($path);
$result = Dropbox::files()->upload('home_pics/'.$name, fopen($imagePath, 'rb'));
```

After uploading the file, I can upload a file successfully but the file is uploaded with 0 bites.

I am confused with the passed parameters. The first parameter is the path of dropbox. But I cannot understand what will be second parameter. 

Inside library, I have seen the following code.

```
$response = $client->post("https://content.dropboxapi.com/2/files/upload", [
                'headers' => [
                    'Authorization' => 'Bearer '.$this->getAccessToken(),
                    'Dropbox-API-Arg' => json_encode([
                        'path' => $path,
                        'mode' => 'add',
                        'autorename' => true
                    ]),
                    'Content-Type' => 'application/octet-stream',
                    'data-binary' => "@$file"
                ]
            ]);

```
I don't know what will be a value inside **$file**. Can anyone please help?

**Comment by dcblogdev** [comment]
Apologies for the delay, this has now been fixed, please run `composer update` to pull down the latest release.

**Comment by ppalashturov** [comment]
I don`t install latest version and have a problem with upload image!
Please Help me.

**Comment by ppalashturov** [comment]
> Apologies for the delay, this has now been fixed, please run `composer update` to pull down the latest release.

Don`t Work!!!
