### ISSUE TITLE
FileSize Upload

### ISSUE THREAD

**Issue by ppalashturov** [dcblogdev/laravel-dropbox#3]
This fixed don`t worked:
https://github.com/dcblogdev/laravel-dropbox/issues/2

**Comment by ppalashturov** [comment]
Problem 1
    - The requested package daveismyname/laravel-dropbox ^1.0.3 exists as daveismyname/laravel-dropbox[dev-master, v1.0.0, v1.0.1, v1.0.2] but these are rejected by your constraint.

**Comment by dcblogdev** [comment]
I've rebranded and issues a new release update your composer to `"dcblogdev/laravel-dropbox": "^2.0"` and try again

**Comment by ppalashturov** [comment]
I don`t upload please help me:
$file = $request->file('file');
$filename = $request->file->getClientOriginalName();
Dropbox::files()->upload($filename, $file );

**Comment by dcblogdev** [comment]
this works for me:

```php
$filename = public_path('test.txt');
$uploadPath = 'test2.txt';
return Dropbox::files()->upload($filename, $uploadPath);
```

in your code ensure the paths are correct for uploading from.

**Comment by ppalashturov** [comment]
Thanks for the reply, the file should be located on the server, it is described to do the upload action form.

**Comment by ppalashturov** [comment]
I have a problem with Windows path example:
"D:\laragon\www\dropbox\storage\app\uploads/negative-ltd.pdf"

Error: 
Exception
fopen(/negative-ltd.pdf): failed to open stream: No such file or directory
http://dropbox.test/upload

**Comment by ppalashturov** [comment]
Is there an option to not upload the file to the server?

**Comment by dcblogdev** [comment]
not that I know of.
